from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import pandas as pd

try:
    sys.stdout.reconfigure(encoding="utf-8")
except Exception:
    pass

REPO = Path(__file__).resolve().parents[1]
IRT = REPO / "data" / "irt"
OUT = REPO / "data" / "gpt_scaling"
OUT.mkdir(parents=True, exist_ok=True)

SEED = 20260721          # fixed: the sample must be reproducible
TARGET = 1000            # documents per corpus
US_PER_PARTY = 500       # US: two parties, 500 each


def _frame(corpus: str) -> pd.DataFrame:
    """doc_id + party for every estimation-sample document of the corpus."""
    z = np.load(IRT / f"irt_matrices_{corpus}.npz", allow_pickle=True)
    return pd.DataFrame({"doc_id": z["docs"].astype(str), "party": z["party"].astype(str)})


def allocate_capped(counts: dict[str, int], total: int) -> dict[str, int]:
    """Capped equal allocation (water-filling) to exactly `total`.

    Every party targets total/P documents; a party with fewer than its share
    contributes all it has and its shortfall is redistributed equally over the
    parties that still have spare capacity.  The last integer remainder is given
    to the highest-capacity parties so the allocation sums to `total` exactly and
    never exceeds any party's available count.
    """
    alloc = {p: 0 for p in counts}
    uncapped = set(counts)
    remaining = total
    while uncapped:
        level = remaining / len(uncapped)
        capped = [p for p in uncapped if counts[p] <= level]
        if not capped:
            break
        for p in capped:
            alloc[p] = counts[p]
            remaining -= counts[p]
            uncapped.discard(p)
    if uncapped:
        u = sorted(uncapped)
        base = remaining // len(u)
        for p in u:
            alloc[p] = base
        rem = remaining - base * len(u)
        for p in sorted(u, key=lambda q: (-counts[q], q))[:rem]:
            alloc[p] += 1
    assert sum(alloc.values()) == total, (sum(alloc.values()), total)
    assert all(alloc[p] <= counts[p] for p in counts), "allocation exceeds availability"
    return alloc


def sample_group(df: pd.DataFrame, alloc: dict[str, int], rng) -> pd.DataFrame:
    parts = []
    for party, k in alloc.items():
        pool = df.loc[df.party == party, "doc_id"].to_numpy()
        take = rng.choice(pool, size=k, replace=False)
        parts.append(pd.DataFrame({"doc_id": take, "party": party}))
    return pd.concat(parts, ignore_index=True)


def main() -> int:
    rng = np.random.default_rng(SEED)
    lines: list[str] = []

    def log(msg=""):
        print(msg)
        lines.append(msg)

    log("# GPT ask-and-average — stratified document samples")
    log("")
    log(f"Two samples of {TARGET:,} documents each, drawn without replacement from "
        "the estimation-sample documents, for the LLM scaling baseline of Le Mens & "
        "Gallego (2025). The document is the sampling unit; its sentence-chunks are "
        "scored and averaged.")
    log(f"\nSeed: `{SEED}`.  Generated by `code/40D_gpt_sample.py`.")

    # ---- United States: 500 per party ------------------------------------- #
    us = _frame("us")
    counts_us = us.party.value_counts().to_dict()
    alloc_us = {p: US_PER_PARTY for p in ["Democrat", "Republican"]}
    samp_us = sample_group(us, alloc_us, rng).sample(frac=1.0, random_state=SEED).reset_index(drop=True)
    samp_us.to_csv(OUT / "gpt_sample_us.csv", index=False, encoding="utf-8")

    log("\n## United States")
    log(f"\n{len(us):,} estimation-sample candidate--cycle platforms; "
        f"sample = {US_PER_PARTY} per party.\n")
    log("| Party | Available | Sampled |")
    log("|---|---:|---:|")
    for p in ["Democrat", "Republican"]:
        log(f"| {p} | {counts_us.get(p, 0):,} | {alloc_us[p]:,} |")
    log(f"| **Total** | **{len(us):,}** | **{len(samp_us):,}** |")

    # ---- Brazil: capped equal allocation ---------------------------------- #
    br = _frame("br")
    counts_br = br.party.value_counts().to_dict()
    alloc_br = allocate_capped(counts_br, TARGET)
    samp_br = sample_group(br, alloc_br, rng).sample(frac=1.0, random_state=SEED).reset_index(drop=True)
    samp_br.to_csv(OUT / "gpt_sample_br.csv", index=False, encoding="utf-8")

    fair = TARGET / len(counts_br)
    n_capped = sum(alloc_br[p] == counts_br[p] and counts_br[p] < fair for p in counts_br)
    log("\n## Brazil (mayoral platforms only)")
    log(f"\n{len(br):,} estimation-sample mayoral platforms across {len(counts_br)} parties. "
        f"Equal quota would be {fair:.1f} per party; {n_capped} parties smaller than that "
        "contribute all their platforms and the shortfall is spread over the larger parties "
        "(capped equal allocation).\n")
    log("| Party | Available | Target/allocated | Sampled |")
    log("|---|---:|---:|---:|")
    got_br = samp_br.party.value_counts().to_dict()
    for p in sorted(counts_br, key=lambda q: (-alloc_br[q], q)):
        flag = "  *(all)*" if alloc_br[p] == counts_br[p] and counts_br[p] < fair else ""
        log(f"| {p}{flag} | {counts_br[p]:,} | {alloc_br[p]:,} | {got_br.get(p, 0):,} |")
    log(f"| **Total** | **{len(br):,}** | **{sum(alloc_br.values()):,}** | **{len(samp_br):,}** |")

    log("\n---\n")
    log("`gpt_sample_{us,br}.csv` columns: `doc_id, party`. The classifier "
        "(`code/40E_gpt_classify.py`) expands each document to its sentence-chunks "
        "and scores them; `code/40F_gpt_ideal_points.py` averages the numeric scores "
        "(dropping non-political NAs) up to the document and, for Brazil, the party.")

    (OUT / "SAMPLE_DESIGN.md").write_text("\n".join(lines) + "\n", encoding="utf-8")

    print(f"\nwrote {(OUT / 'gpt_sample_us.csv').relative_to(REPO)}  ({len(samp_us):,} docs)")
    print(f"wrote {(OUT / 'gpt_sample_br.csv').relative_to(REPO)}  ({len(samp_br):,} docs)")
    print(f"wrote {(OUT / 'SAMPLE_DESIGN.md').relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
