from __future__ import annotations
import sys
from pathlib import Path
import numpy as np
import pandas as pd

try:
    sys.stdout.reconfigure(encoding="utf-8")
except Exception:
    pass

HERE = Path(__file__).resolve().parent
REPO = HERE.parent
DATA = REPO / "data"
OUT = REPO / "paper" / "sections" / "tables" / "corpus_composition.tex"

NONPLATFORM_FILE = DATA / "br" / "nonplatform_br.csv"


def _t(n: int) -> str:
    return f"{n:,}".replace(",", "{,}")


def _kinds_table(z) -> None:
    """The excluded documents by kind, and how many of each reached the fit."""
    conf = pd.read_csv(NONPLATFORM_FILE, dtype={"doc": str})
    scal = (set(z["nonplatform_scalable"].astype(str))
            if "nonplatform_scalable" in z.files else set())
    conf["reached"] = conf.doc.isin(scal)
    g = (conf.groupby("kind")
         .agg(n=("doc", "size"), reached=("reached", "sum"))
         .sort_values("n", ascending=False))
    body = "\n".join(f"{k[0].upper() + k[1:]} & {int(r.n)} & {int(r.reached)} \\\\"
                     for k, r in g.iterrows())
    rows = [
        r"% GENERATED by code/50C_corpus_composition.py -- do not edit by hand.",
        r"\begin{table}[ht]", r"\centering",
        r"\caption{Documents Excluded as Filings Rather Than Platforms}",
        r"\label{tab:nonplatform-kinds}",
        r"\begin{threeparttable}",
        r"\begin{tabular}{@{}lrr@{}}", r"\toprule",
        r"Kind of document & Excluded & Would have been scaled \\",
        r"\midrule", body, r"\midrule",
        rf"Total & {int(g.n.sum())} & {int(g.reached.sum())} \\",
        r"\bottomrule", r"\end{tabular}",
        r"\begin{tablenotes}[flushleft]", r"\footnotesize",
        r"\item Every document listed here was read whole and confirmed not to be a campaign "
        r"platform. \emph{Excluded} counts the documents in the whole Brazilian corpus; "
        r"\emph{Would have been scaled} counts those carrying at least ten sentences, so "
        r"that the length floor would not have removed them anyway. Kinds are the screen's own "
        r"categories, described in Appendix~\ref{app:composition}.",
        r"\end{tablenotes}", r"\end{threeparttable}", r"\end{table}", "",
    ]
    out = OUT.parent / "nonplatform_kinds.tex"
    out.write_text("\n".join(rows), encoding="utf-8")
    print(f"wrote {out.relative_to(REPO)}")
    print(g.to_string())

    scan = pd.read_csv(DATA / "br" / "nonplatform_screen_br.csv", dtype={"doc": str})
    scalable = len(scal)
    macros = OUT.parent / "nonplatform_numbers.tex"
    macros.write_text(
        "%% auto-generated by code/50C_corpus_composition.py -- do not edit\n"
        f"\\newcommand{{\\nNonPlatform}}{{{len(conf)}}}\n"
        f"\\newcommand{{\\nNonPlatformFlagged}}{{{len(scan)}}}\n"
        f"\\newcommand{{\\nNonPlatformFit}}{{{scalable}}}\n", encoding="utf-8")
    print(f"wrote {macros.relative_to(REPO)}: confirmed {len(conf)}, "
          f"flagged {len(scan)}, scalable {scalable}")


def main() -> int:
    pm = pd.read_feather(DATA / "br" / "platform_party_map.feather")
    pm["platform_id"] = pm.platform_id.astype(str)
    if "has_pdf" not in pm.columns:
        raise KeyError("platform_party_map.feather lacks has_pdf; run data/br/05_add_pdf_flag.py")
    corpus_ids = set(pd.read_feather(DATA / "br" / "br_manifestos_chunks_sent.feather",
                                     columns=["doc_id"]).doc_id.astype(str).unique())
    pm["in_corpus"] = pm.platform_id.isin(corpus_ids)
    vm = pm.valid_mayor_platform

    n_candidates = int(vm.sum())                          # all 2020 ordinary mayoral candidates (TSE)
    n_all_pdf = int(pm.has_pdf.sum())                     # every collected campaign-platform PDF
    n_may_pdf = int((vm & pm.has_pdf).sum())              # mayoral platforms with a PDF
    n_may_parsed = int((vm & pm.in_corpus).sum())         # mayoral platforms parsed to text
    z = np.load(DATA / "irt" / "irt_matrices_br.npz", allow_pickle=True)
    n_model = int(z["N"])

    n_nonmayoral_pdf = int((~vm & pm.has_pdf).sum())      # PDFs filed for a non-mayoral office
    n_no_pdf = n_candidates - n_may_pdf                   # mayoral candidates with no recoverable PDF
    n_unparsed = n_may_pdf - n_may_parsed                 # PDFs that failed to parse
    # Filings that are not platforms, removed by the screen in 04_irt_data.py before the
    # length floor applies; the ids are persisted with the matrices.
    n_filing = int(len(z["nonplatform"])) if "nonplatform" in z.files else 0
    n_confirmed = int(len(pd.read_csv(NONPLATFORM_FILE, dtype={"doc": str})))
    zu = np.load(DATA / "irt" / "irt_matrices_us.npz", allow_pickle=True)
    n_us_model = int(zu["N"])
    n_us_all = int(pd.read_feather(DATA / "us" / "campaignview_chunks_sent.feather",
                                   columns=["doc_id"]).doc_id.nunique())
    n_after_filing = n_may_parsed - n_filing
    n_short = n_after_filing - n_model                    # remaining platforms below the 10-chunk floor

    rows = [
        r"% GENERATED by code/50C_corpus_composition.py -- do not edit by hand.",
        r"\begin{table}[ht]", r"\centering",
        r"\caption{Composition of the Brazilian Mayoral Corpus}",
        r"\label{tab:corpus-composition}",
        r"\begin{threeparttable}",
        r"\begin{tabular}{@{}lr@{}}", r"\toprule",
        r"Stage & Documents \\",
        r"\midrule",
        rf"Mayoral candidates, 2020 ordinary election\tnote{{a}} & {_t(n_candidates)} \\",
        rf"Municipal campaign platforms collected as PDF\tnote{{b}} & {_t(n_all_pdf)} \\",
        rf"\quad mayoral platforms with a PDF & {_t(n_may_pdf)} \\",
        rf"\quad mayoral platforms parsed to text & {_t(n_may_parsed)} \\",
        rf"\quad after removing filings that are not platforms\tnote{{c}} & {_t(n_after_filing)} \\",
        rf"\quad entering the estimation sample ($\geq 10$ sentences) & {_t(n_model)} \\",
        r"\bottomrule",
        r"\end{tabular}",
        r"\begin{tablenotes}[flushleft]",
        r"\footnotesize",
        rf"\item[a] The universe of candidates who contested a mayoralty in the 2020 ordinary "
        rf"municipal election, from the TSE candidate microdata \citep{{tse2020cand}}.",
        rf"\item[b] The collected campaign-platform PDFs, filed with the electoral authority. "
        rf"{_t(n_nonmayoral_pdf)} were filed for a non-mayoral office (vice-mayor, city councilor, "
        rf"supplementary-election mayor) and are excluded from every model in the paper.",
        rf"\item[c] Documents filed under a candidate's name that are not campaign platforms: a "
        rf"power of attorney, a court filing, a clearance certificate, a filing receipt, a consent "
        rf"form, party convention minutes, a campaign workbook, a printout of the candidate's "
        rf"registry page. {_t(n_confirmed)} such documents were identified across the whole corpus "
        rf"and read whole; {n_filing} of them survive to this row, the rest having already failed "
        rf"to parse or been filed for another office. Appendix~\ref{{app:composition}} describes "
        rf"the screen and the reading.",
        rf"\item Of the {_t(n_candidates)} mayoral candidates, {_t(n_no_pdf)} filed no recoverable "
        rf"platform; a further {n_unparsed} PDFs could not be parsed from their scanned image, "
        rf"{n_filing} were filings rather than platforms, and "
        rf"{n_short} parsed platforms fell below the ten-sentence minimum. The United States corpus "
        rf"needs no such funnel: all {_t(n_us_all)} collected platforms belong to congressional "
        rf"candidates, and {_t(n_us_model)} enter the estimation sample under the same rule.",
        r"\end{tablenotes}",
        r"\end{threeparttable}",
        r"\end{table}", "",
    ]
    OUT.write_text("\n".join(rows), encoding="utf-8")
    _kinds_table(z)

    print("Brazilian mayoral corpus funnel:")
    print(f"  mayoral candidates (2020 ordinary, TSE) : {n_candidates:,}")
    print(f"  campaign platforms collected as PDF     : {n_all_pdf:,}  ({n_nonmayoral_pdf:,} non-mayoral)")
    print(f"  mayoral platforms with a PDF            : {n_may_pdf:,}  ({n_no_pdf:,} candidates had none)")
    print(f"  mayoral platforms parsed to text        : {n_may_parsed:,}  ({n_unparsed} PDFs unparsed)")
    print(f"  after removing non-platform filings     : {n_after_filing:,}  ({n_filing} filings)")
    print(f"  used in the model (>=10 chunks)         : {n_model:,}  ({n_short} below floor)")
    print(f"\nwrote {OUT.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
