from __future__ import annotations

import importlib.util
import sys
from pathlib import Path

import numpy as np

try:
    sys.stdout.reconfigure(encoding="utf-8")
except Exception:
    pass

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[0]
IRT = REPO / "data" / "irt"
OUT = REPO / "paper" / "tables"

_spec = importlib.util.spec_from_file_location("irt_data07", HERE / "04_irt_data.py")
irt_data = importlib.util.module_from_spec(_spec)
sys.modules["irt_data07"] = irt_data
_spec.loader.exec_module(irt_data)

_ms = importlib.util.spec_from_file_location("macro_irt_data", HERE / "04B_macro_irt_data.py")
macro_data = importlib.util.module_from_spec(_ms)
sys.modules["macro_irt_data"] = macro_data
_ms.loader.exec_module(macro_data)

BR_LEFT_CUT = irt_data.BR_LEFT_CUT

# Captions, verbatim as they appear in the paper.  Keys double as \label suffixes
# and as output filenames.  No table numbers anywhere.
TITLES = {
    "positions_by_group": "Estimated Positions by Party Group",
    "positions_by_party_br": "Estimated Positions by Party, Brazil",
}

MODE = "godambe"          # the fit the paper reports

# Brazilian party labels are acronyms and stay uppercase; these are the ones that
# are read as words, plus the bucket for parties the expert survey does not cover.
PRETTY_BR = {
    "PC DO B": "PC do B", "UNKNOWN": "Unmatched", "AVANTE": "Avante",
    "CIDADANIA": "Cidadania", "PATRIOTA": "Patriota", "REDE": "Rede",
    "NOVO": "Novo", "REPUBLICANOS": "Republicanos", "PODE": "Podemos",
    "SOLIDARIEDADE": "Solidariedade",
}


# --------------------------------------------------------------------------
# data
# --------------------------------------------------------------------------
def load(corpus):
    """Persisted theta plus the metadata needed to group it.  Never refits.

    The main fit is the supertopic fit, and dropping its boilerplate column
    empties a handful of documents, so the metadata comes back already cut to
    the documents the fit kept.
    """
    F, D = macro_data.load_main(corpus, MODE)
    theta = F["theta"].astype(float)
    party = np.asarray(D["party"]).astype(str)
    ext = np.asarray(D["ext"]).astype(float) if corpus == "br" else None
    if len(theta) != len(party):
        raise ValueError(f"[{corpus}] theta {len(theta)} vs party {len(party)}: stale cache")
    return theta, party, ext


def groups(corpus, party, ext):
    """The paper's grouping.  Brazil's blocs are the poster's expert-score split."""
    if corpus == "us":
        return [("Democrat", party == "Democrat"), ("Republican", party == "Republican")]
    fin = np.isfinite(ext)
    blocs = [("Left bloc", fin & (ext <= BR_LEFT_CUT)),
             ("Non-left", fin & (ext > BR_LEFT_CUT))]
    if (~fin).any():                      # only when some party lacks an expert score
        blocs.append(("No expert score", ~fin))
    return blocs


def summarize(theta, mask):
    x = theta[mask]
    return dict(n=int(mask.sum()), mean=float(x.mean()), median=float(np.median(x)),
                sd=float(x.std(ddof=1)))


# --------------------------------------------------------------------------
# LaTeX
# --------------------------------------------------------------------------
def _num(x):
    return f"{x:{'+.3f' if x else '.3f'}}".replace("+", r"$+$").replace("-", r"$-$")


def _float(key, body, notes):
    return "\n".join([
        r"% GENERATED by code/50D_descriptive_tables.py -- do not edit by hand.",
        r"\begin{table}[t]", r"\centering",
        rf"\caption{{{TITLES[key]}}}",
        rf"\label{{tab:{key.replace('_', '-')}}}",
        r"\begin{threeparttable}", body,
        r"\begin{tablenotes}[flushleft]", r"\footnotesize", notes,
        r"\end{tablenotes}", r"\end{threeparttable}", r"\end{table}", "",
    ])


def table_positions_by_group(stats):
    rows = [r"\begin{tabular}{@{}lrrrr@{}}", r"\toprule",
            r" & $N$ & Mean & Median & SD \\"]
    for corpus, label in (("us", "United States"), ("br", "Brazil")):
        rows += [r"\midrule", rf"\multicolumn{{5}}{{@{{}}l}}{{\emph{{{label}}}}} \\"]
        for name, s in stats[corpus]:
            rows.append(f"{name} & {s['n']:,} & {_num(s['mean'])} & "
                        f"{_num(s['median'])} & {s['sd']:.3f} \\\\".replace(",", "{,}"))
    rows += [r"\bottomrule", r"\end{tabular}"]

    us = dict(stats["us"])
    ratio = -us["Republican"]["mean"] / us["Democrat"]["mean"]
    n_ratio = us["Democrat"]["n"] / us["Republican"]["n"]
    n_unscored = dict(stats["br"]).get("No expert score", {}).get("n", 0)

    if n_unscored > 0:
        br_note = (rf"\item Brazil's blocs split the parties at the expert score of REDE "
                   rf"(${BR_LEFT_CUT}$, \citealp{{bolognesi2023new}}). They do not exhaust the "
                   rf"corpus: {n_unscored} documents come from parties the expert survey does not "
                   rf"cover, so the two bloc means are not mirror images.")
    else:
        br_note = (rf"\item Brazil's blocs split the parties at the expert score of REDE "
                   rf"(${BR_LEFT_CUT}$, \citealp{{bolognesi2023new}}). Every party in the "
                   rf"mayoral corpus carries an expert score, so the two blocs exhaust it and the "
                   rf"same centering identity holds: the bloc means are mirror images up to the "
                   rf"bloc sizes, and only the separation between them is identified.")

    notes = "\n".join([
        rf"\item Ideal points from the joint fit, identified by $\sum_i \theta_i = 0$ and "
        rf"$\frac{{1}}{{T}}\sum_t \beta_t^2 = 1$; the scale is therefore set by the stance "
        rf"loadings, not by $\mathrm{{Var}}(\theta)$, and the standard deviations are not $1$.",
        rf"\item Because the two US parties exhaust that corpus, centering forces "
        rf"$n_D\bar\theta_D = -n_R\bar\theta_R$: the ratio of the party means, "
        rf"${ratio:.4f}$, is the ratio of the party counts, ${n_ratio:.4f}$. The party "
        rf"means carry no information the separation between them does not.",
        br_note,
    ])
    return _float("positions_by_group", "\n".join(rows), notes)


def table_positions_by_party_br(theta, party, ext, min_docs=25):
    esc = {p: float(ext[party == p][0]) for p in np.unique(party)}
    keep = [p for p in np.unique(party) if (party == p).sum() >= min_docs]
    keep.sort(key=lambda p: (np.nan_to_num(esc[p], nan=1e9), p))
    dropped = int(len(np.unique(party)) - len(keep))

    rows = [r"\begin{tabular}{@{}lrrrrr@{}}", r"\toprule",
            r"Party & Expert & $N$ & Mean & Median & SD \\", r"\midrule"]
    for p in keep:
        s = summarize(theta, party == p)
        e = esc[p]
        e_s = "--" if not np.isfinite(e) else f"{e:.2f}"
        rows.append(f"{PRETTY_BR.get(p, p)} & {e_s} & {s['n']:,} & {_num(s['mean'])} & "
                    f"{_num(s['median'])} & {s['sd']:.3f} \\\\".replace(",", "{,}"))
    rows += [r"\bottomrule", r"\end{tabular}"]

    notes = "\n".join([
        rf"\item Parties with at least {min_docs} platforms, ordered by the expert "
        rf"left--right score of \citet{{bolognesi2023new}}; {dropped} smaller parties are "
        rf"omitted from the table but not from the estimation. ``Expert'' is the party's "
        rf"expert score, lower being further left; it is a party-level quantity and is "
        rf"never imputed to individual candidates.",
        r"\item Ideal points are centered across the whole corpus, so the "
        r"document-weighted mean of the column is zero by construction. Differences "
        r"between parties are identified; the level of any one party mean is not.",
    ])
    return _float("positions_by_party_br", "\n".join(rows), notes)


# --------------------------------------------------------------------------
def main():
    OUT.mkdir(parents=True, exist_ok=True)

    stats, raw = {}, {}
    for corpus in ("us", "br"):
        theta, party, ext = load(corpus)
        raw[corpus] = (theta, party, ext)
        stats[corpus] = [(name, summarize(theta, m)) for name, m in groups(corpus, party, ext)]
        print(f"[{corpus}] N={len(theta):,}  mean={theta.mean():+.2e}  sd={theta.std():.4f}")
        for name, s in stats[corpus]:
            print(f"    {name:<16} n={s['n']:>6,}  mean={s['mean']:+.4f}  "
                  f"median={s['median']:+.4f}  sd={s['sd']:.4f}")

    written = {
        "positions_by_group": table_positions_by_group(stats),
        "positions_by_party_br": table_positions_by_party_br(*raw["br"]),
    }
    for key, tex in written.items():
        path = OUT / f"{key}.tex"
        path.write_text(tex, encoding="utf-8")
        print(f"\n--- {path.relative_to(REPO)}  ({TITLES[key]})\n{tex}")


if __name__ == "__main__":
    main()
