from __future__ import annotations

import importlib.util
import os
import sys
from pathlib import Path

import numpy as np

try:
    sys.stdout.reconfigure(encoding="utf-8")
except Exception:
    pass

HERE = Path(__file__).resolve().parent
REPO = Path(os.getenv("TOPIC2IRT_ROOT", HERE.parents[0]))
OUT = REPO / "paper" / "sections" / "tables"
OUT.mkdir(parents=True, exist_ok=True)

sys.path.insert(0, str(HERE))
import macro_topics as mt  # noqa: E402

_ms = importlib.util.spec_from_file_location("macro_irt_data",
                                             HERE / "04B_macro_irt_data.py")
macro_data = importlib.util.module_from_spec(_ms)
sys.modules["macro_irt_data"] = macro_data
_ms.loader.exec_module(macro_data)

CORPUS_NAME = {"us": "United States", "br": "Brazil"}


def _tex(s: str) -> str:
    return (str(s).replace("&", r"\&").replace("%", r"\%").replace("_", r"\_")
            .replace("#", r"\#"))


def build(corpus: str) -> str:
    S = mt.CROSSWALK[mt.CROSSWALK.Corpus == corpus.upper()]
    D = macro_data.load_matrices("macro", corpus, verbose=False)
    n_sent = dict(zip([str(t) for t in D["tops"]],
                      np.asarray(D["Y"].sum(0)).ravel().astype(int)))
    total = sum(n_sent.values())

    blocks: dict = {}
    for code in mt.classes_present(corpus):
        blocks.setdefault(mt.BLOCK[code], []).append(code)

    body = []
    first = True
    for block, codes in blocks.items():
        if not first:
            body.append(r"\addlinespace")
        first = False
        # \\* keeps a dimension heading from being left alone at the foot of a
        # page with its first class on the next one.  Class rows carry no extra
        # spacing so each corpus's table fits on one page.
        body.append(rf"\multicolumn{{3}}{{@{{}}l}}{{\emph{{{_tex(block)}}}}} \\*")
        for code in codes:
            members = S[S["Macro Code"] == code]["Topic Label"].tolist()
            share = 100.0 * n_sent.get(code, 0) / total
            name = _tex(mt.LABEL[code])
            if code == mt.BOILERPLATE_CODE:
                name += r"$^{\dagger}$"
            # semicolons, not commas: several subtopic labels contain a comma
            # ("Youth, Children & Adolescents"), so a comma list cannot be read
            body.append(rf"{name} & {share:.1f} & "
                        + _tex("; ".join(sorted(members))) + r" \\")

    n_fine = len(S)
    n_boiler = int((S["Macro Code"] == mt.BOILERPLATE_CODE).sum())
    note = (
        rf"\item All {n_fine} subtopics the topic model discovers in the "
        rf"{CORPUS_NAME[corpus]} corpus are listed, each assigned by hand to one "
        rf"supertopic of the codebook, against the subtopic's own sentences rather "
        rf"than its label or its key terms. The supertopic is the unit the model "
        rf"estimates: the columns of $(Y_{{it}}, S_{{it}})$ are summed within it, and "
        rf"the documents and the sentences are untouched. The percentage is the share "
        rf"of the corpus's sentences the supertopic carries. Subtopics are listed by "
        rf"the label assigned to them and separated by semicolons, because several "
        rf"labels contain a comma."
    )
    if n_boiler:
        note += (rf" $^{{\dagger}}$Boilerplate collects the {n_boiler} format and "
                 rf"register subtopics, and the estimates drop it.")

    # Small type, single spacing, and no inter-row space so that each corpus's
    # crosswalk sits on one page; longtable still breaks gracefully if a future
    # codebook outgrows the page.
    head = [rf"\caption{{Subtopics Grouped into Supertopics, "
            rf"{CORPUS_NAME[corpus]}}}",
            rf"\label{{tab:macro-crosswalk-{corpus}}} \\",
            r"\toprule", r"Supertopic & \% & Subtopics \\", r"\midrule",
            r"\endfirsthead",
            rf"\caption[]{{Subtopics Grouped into Supertopics, "
            rf"{CORPUS_NAME[corpus]} \emph{{(continued)}}}} \\",
            r"\toprule", r"Supertopic & \% & Subtopics \\", r"\midrule",
            r"\endhead",
            r"\midrule",
            # the note spans all three columns, so its width has to discount the
            # inter-column \hspace{8pt}; \linewidth alone overruns the text block
            rf"\multicolumn{{3}}{{@{{}}p{{\dimexpr\linewidth-8pt\relax}}@{{}}}}"
            rf"{{\scriptsize {note[6:]}}} \\",
            r"\endlastfoot"]
    return "\n".join([
        r"% GENERATED by code/50H_macro_crosswalk_table.py -- do not edit by hand.",
        r"\begingroup", r"\scriptsize", r"\singlespacing",
        r"\renewcommand{\arraystretch}{1.0}",
        r"\setlength{\LTcapwidth}{\textwidth}",
        r"\begin{longtable}{@{}p{3.2cm}r@{\hspace{8pt}}p{11.3cm}@{}}",
        *head, *body,
        r"\end{longtable}", r"\endgroup", "",
    ])


def audit(corpus: str) -> None:
    """Every subtopic must appear exactly once, boilerplate and residual included.

    The table is what the author validates the hand assignment against, so a
    subtopic missing from it is a silent hole in that check.
    """
    S = mt.CROSSWALK[mt.CROSSWALK.Corpus == corpus.upper()]
    listed = [lab for code in mt.classes_present(corpus)
              for lab in S[S["Macro Code"] == code]["Topic Label"]]
    missing = sorted(set(S["Topic Label"]) - set(listed))
    if missing or len(listed) != len(S):
        raise SystemExit(f"{corpus}: table lists {len(listed)} of {len(S)} "
                         f"subtopics; missing {missing}")
    counts = S["Macro Code"].value_counts()
    print(f"  {corpus}: {len(listed)}/{len(S)} subtopics listed across "
          f"{len(counts)} supertopics, "
          f"boilerplate {int(counts.get(mt.BOILERPLATE_CODE, 0))}, "
          f"residual {int(counts.get(mt.RESIDUAL_CODE, 0))}")


def main():
    for c in ("us", "br"):
        p = OUT / f"macro_crosswalk_{c}.tex"
        p.write_text(build(c), encoding="utf-8")
        print(f"wrote {p.name}")
        audit(c)


if __name__ == "__main__":
    main()
